### ISSUE TITLE
Work with Monorepo (Flow is initializing...)

### ISSUE THREAD

**Issue by natew** [flowtype/ide-flowtype#26] opened 2017-09-15 21:20 UTC
I get this when I install ide and ui:

![image](https://user-images.githubusercontent.com/12100/30503601-b842874e-9a1f-11e7-8c03-1ca1c5536e93.png)

I think this is because ide-flowtype isn't looking for .flowconfig files in the project, and instead is just running flow on root. If I add a .flowconfig to root, I can get it to run. I tried having it just [include] the sub-folders that have .flowconfigs in them, but it doesn't seem to use those configs.

Basic request here would be to add support for finding and *only* parsing sub-folders that have .flowconfig in them.

**Comment by wbinnssmith** [comment] 2017-09-15 21:28
Thanks for reporting @natew. I'd argue this is a duplicate of #13. Feel free reopen and clarify if not.

**Closed by wbinnssmith** 2017-09-15 21:28 UTC
